### ISSUE TITLE
Erro na parte da compilação

### ISSUE THREAD

**Issue by vitoriadevalois** [diegoenriquecardoso/c-language-in-cs50#1]
Olá, encontrei um erro no tópico referente à "Compilação", na **introducao.md**.

No código `make <nome-do-programa.c>`, retire o **.c** 
Para o funcionamento do código, basta  `make <nome-do-programa>`

👍

**Comment by diegoenriquecardoso** [comment]
Eu averiguei e tem toda razão, muito obrigado por apontar essa incongruência.
Lhe agradeço pela ajuda e espero poder lhe ajudar caso veja alguma incoerência em seus repositórios também!
Quero que continue criando issues caso venha a notar mais algum problema.
Para mim a contribuição mútua é muito importante neste site, obrigado!
